# Generated by Django 2.2.10 on 2021-07-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personquestion',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
