# Generated by Django 2.2.10 on 2021-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210707_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personquestion',
            old_name='age',
            new_name='how_many_years',
        ),
        migrations.AlterField(
            model_name='personquestion',
            name='male',
            field=models.CharField(max_length=30),
        ),
    ]
