# Generated by Django 2.2.10 on 2021-07-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210707_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='personquestion',
            name='description',
            field=models.CharField(default='что-то', max_length=100),
        ),
    ]
