# Generated by Django 2.2.10 on 2021-07-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210707_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personquestion',
            name='begin',
        ),
    ]
