# Generated by Django 2.2.10 on 2021-07-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_personquestion_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='personquestion',
            name='begin',
            field=models.DateField(default='2015-02-12'),
        ),
    ]
