# Generated by Django 2.2.10 on 2021-07-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_personquestion_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(max_length=40)),
                ('text_question', models.CharField(max_length=200)),
                ('personquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='SelectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=100)),
                ('personquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='FullMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('send_time', models.DateField(auto_now_add=True)),
                ('personquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_note', models.CharField(max_length=200)),
                ('answer_note', models.CharField(max_length=200)),
                ('fullmessages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FullMessages')),
                ('personquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonQuestion')),
            ],
        ),
    ]
